#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  8 11:48:57 2019

@author: home
"""

#1.2 Getting started with NLTK
"""
import nltk
nltk.download()
from nltk.book import * #import basic books and corpus
"""
#1.3 Searching Text
#concordance view shows every occurrence of word alongside context
text1.concordance("monstrous")
#show words appearing in similar range of contexts
text1.similar("monstrous")
#show context shared by multiple words
text2.common_contexts(["monstrous","very"])
#create dispersion plot of words in a text
text4.dispersion_plot(["citizens","democracy","freedom","duties","America"])
#Generate random text of same style as original text (not in NLTK 3.0)
text3.generate()

#1.4 Counting Vocabulary
#Find #of words and punctuation (tokens) in text
len(text3)
#Obtain vocabulary of text with:
set(text3)
#sorted vocabulary
sorted(set(text3))
#length of vocabulary
len(set(text3))
#Measure % of distinct words in text
len(set(text3))/len(text3)
#Count occurrences of specific word
text3.count("light")
#Occurrences of word as % of total text
100*(text4.count("a")/len(text4))
#Function to measure lexical diversity and calculate percentage
def lexical_diversity(text):
    return len(set(text))/len(text)
def percentage(count,total):
    return 100*(count/total)

"""
2: Closer look at Python - Texts as lists of words
"""
#2.1 Lists
#Text represented as list of tokens
sent1
len(sent1)
lexical_diversity(sent1)
